[package]
name = "provision_profile_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
cms = "0.2.3"
comfy-table = "7.1.1"
der = { version = "0.7.9", features = ["std"] }
dirs = "5.0.1"
plist = "1.7.0"
