name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release # --verbose
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: target/release/pputil
    - name: Run tests
      run: cargo test --release # --verbose
