name: Push at Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release # --verbose
    - name: TarGz Release
      run: tar -czvf target/release/pputil.tar.gz -C target/release pputil
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          target/release/pputil.tar.gz
          target/release/pputil
    - name: Run tests
      run: cargo test --release # --verbose
    - name: Compile and release
      uses: rust-build/rust-build.action@v1.4.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        RUSTTARGET: ${{ matrix.target }}
        EXTRA_FILES: "README.md LICENSE"
